version: '3'
services:
  web:
    build: .
    ports:
     - 8000:8888
    depends_on:
      - 'db'
    environment:
      DATABASE_URL: postgres://postgres@db/twodo_app_db?sslmode=disable
    volumes:
      - .:/go/src/github.com/lccezinha/twodo
    command: scripts/start
  db:
    image: postgres:9.5
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432
volumes:
  postgres:
