version: '3'
services:
  db:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    depends_on:
      - 'db'
    build: .
    ports:
     - "8000:8888"
volumes:
  postgres:
